# This is the configuration file for Opotato.
#
# The following options can be enabled or disabled if there is a compatibility issue.
# Add a line mixin.example_name=true/false without the # sign to enable/disable a rule.
# All the mixins: 
# mixin.alternatecurrent
# mixin.api
# mixin.mixintrace
# mixin.opotato
# mixin.opotato.arsnouveau
# mixin.opotato.astralsorcery
# mixin.opotato.blueprint
# mixin.opotato.blueskies
# mixin.opotato.brutalbosses
# mixin.opotato.byg
# mixin.opotato.cataclysm
# mixin.opotato.cataclysm.rubidium
# mixin.opotato.cataclysm.rubidium.extra
# mixin.opotato.charm
# mixin.opotato.citadel
# mixin.opotato.deuf
# mixin.opotato.dynamiclights
# mixin.opotato.elenaidodge
# mixin.opotato.forge
# mixin.opotato.gender
# mixin.opotato.headshot
# mixin.opotato.industrialforegoing
# mixin.opotato.itemstages
# mixin.opotato.kiwi
# mixin.opotato.ldlib
# mixin.opotato.modernui
# mixin.opotato.modernui.tooltip
# mixin.opotato.neat
# mixin.opotato.placebo
# mixin.opotato.quark
# mixin.opotato.randompatches
# mixin.opotato.spark
# mixin.opotato.supplementaries
# mixin.opotato.titanium
# mixin.opotato.undergarden
# mixin.opotato.witherstorm
# mixin.opotato.xaerominimap
# mixin.opotato.xaeroworldmap
# mixin.smoothmenu
mixin.opotato.astralsorcery=false
mixin.opotato.blueprint=false
mixin.opotato.blueskies=false
mixin.opotato.brutalbosses=false
mixin.opotato.byg=false
mixin.opotato.charm=false
mixin.opotato.dynamiclights=false
mixin.opotato.elenaidodge=false
mixin.opotato.gender=false
mixin.opotato.headshot=false
mixin.opotato.industrialforegoing=false
mixin.opotato.itemstages=false
mixin.opotato.kiwi=false
mixin.opotato.ldlib=false
mixin.opotato.modernui=false
mixin.opotato.modernui.tooltip=false
mixin.opotato.neat=false
mixin.opotato.quark=false
mixin.opotato.randompatches=false
mixin.opotato.titanium=false
mixin.opotato.undergarden=false
mixin.opotato.witherstorm=false
mixin.opotato.xaerominimap=false
mixin.opotato.xaeroworldmap=false
