
[DeathButThree]
	#Before ';': boss' registry name
	#After ';': its max death times
	ValidBossesAndMaxDeathTimes = ["minecraft:ender_dragon;1", "minecraft:wither;1", "alexsmobs:void_worm;1", "alexsmobs:warped_mosco;1", "ars_nouveau:wilden_boss;1", "bosses_of_mass_destruction:gaunlet;1", "bosses_of_mass_destruction:lich;1", "bosses_of_mass_destruction:obsidilith;1", "bosses_of_mass_destruction:void_blossom;1", "cataclysm:ender_golem;1", "cataclysm:ender_guardian;1", "cataclysm:ignis;1", "cataclysm:ignited_revenant;1", "cataclysm:netherite_monstrosity;1", "iceandfire:cyclops;1", "iceandfire:fire_dragon;1", "iceandfire:hydra;1", "iceandfire:ice_dragon;1", "iceandfire:lightning_dragon;1", "mowziesmobs:barako;1", "mowziesmobs:ferrous_wroughtnaut;1", "mowziesmobs:frostmaw;1"]

