
#Combat Configuration
[combat_configuration]
	#Enable area of effects also being applied to players. 
	#If you do not want area of effects being applied to other players, disable this feature. [true / false]
	enableAreaOfEffectOnOtherPlayers = true
	#Add entities that will never be targeted by aggressive Dungeons effects. 
	#To do so, enter their registry names.
	effectTargetBlacklist = []
	#Enable two handed weapon. 
	#If you do not want two handed weapon, disable this feature. [true / false]
	enableTwoHandedWeapon = false
	#Add entities that should be targetted, but aren't by aggressive Dungeons effects. 
	#To do so, enter their registry names.
	effectTargetWhitelist = ["iceandfire:cockatrice", "iceandfire:cyclops", "iceandfire:fire_dragon", "iceandfire:hydra", "iceandfire:ice_dragon", "iceandfire:lightning_dragon", "iceandfire:sea_serpent", "iceandfire:siren", "iceandfire:stymphalian_bird"]
	#Enable dual wielding. 
	#If you do not want dual wielding, disable this feature. [true / false]
	enableDualWielding = false

#Souls Configuration
[souls_configuration]
	#Enables keeping of souls upon death, disabled by default. [true / false]
	enableKeepSoulsOnDeath = true

#Artifact Configuration
[artifact_configuration]
	#Set the durability for artifacts. [0-1024, default: 64
	#Range: 0 ~ 1024
	artifactDurability = 64

#Elite Mob Configuration
[elite_mob_configuration]
	#Base chance of an elite mob spawning. [0.0 - 1.0] 
	#Calculation: chance * difficulty.getSpecialMultiplier() 
	#Base chance for vanilla armor spawning is 0.15. Default is 0.15
	#Range: 0.0 ~ 1.0
	eliteMobsBaseChance = 0.0
	#Enables elite mobs, enabled by default. [true / false]
	enableEliteMobs = false

