
[endrem]
	#Toggle Vanilla Minecraft Strongholds
	strongholds = false
	#Toggle Whether surrounding land will be modified to conform to the bottom of the structure. 
	# If set to false, the bottom of the structure will be modified to conform to the surrounding land
	end_castle_terraforming = true
	#Average distance in chunks between Ancient Witch Huts (Set to 0 to disable)
	ancient_witch_hut_distance = 50
	#Comma-separated list of whitelisted dimensions for End Remastered Structures
	whitelisted_dimensions = "[minecraft:overworld]"
	#Comma-separated list of whitelisted biome categories for the End Castle
	end_castle_whitelisted_biome_categories = "[none, plains, forest]"
	#Number of pieces generated in End Gates
	end_gate_size = 20
	#Percentage chance of eyes breaking when thrown
	eye_break_chance = 20
	#Toggle Ender Eyes Actions (Throwing and Placing in Portal Frames)
	ender_eyes = false
	#Comma-separated list of blacklisted biomes for the End Castle
	end_castle_blacklisted_biomes = "[minecraft:birch_forest_hills, minecraft:dark_forest_hills, minecraft:tall_birch_hills, minecraft:wooded_hills, projectvibrantjourneys:alpine_heights, projectvibrantjourneys:aspen_grove_hills, projectvibrantjourneys:autumnal_coniferous_forest, projectvibrantjourneys:boreal_forest, projectvibrantjourneys:boreal_plateau, projectvibrantjourneys:crimson_thicket, projectvibrantjourneys:redwood_peaks, projectvibrantjourneys:redwoods, projectvibrantjourneys:snowy_boreal_forest, projectvibrantjourneys:snowy_redwoods]"
	#Y-Coordinate of the starting piece of the End Gate
	end_gate_height = 15
	#Average distance in chunks between End Gates (Set to 0 to disable)
	end_gate_distance = 0
	#Comma-separated list of structures to locate with End Remastered eyes
	eye_structure_list = "[betterstrongholds:stronghold, endrem:end_castle]"
	#Stats for End Remastered's End Crystal armor: [durability factor, defense factor, toughness, knockback resistance, makes piglins neutrals, regen duration (in ticks)]
	end_crystal_armor_stats = "[33, 1, 2, 0.1, true, 20]"
	#Comma-separated list of blacklisted biomes for the End Gate
	end_gate_blacklisted_biomes = "[none]"
	#Minimum distance in chunks between End Castles and the spawn
	end_castle_spawn_distance = 1280
	#Stats for End Remastered's End Crystal tools: [durability, speed, damage bonus]
	end_crystal_tools_stats = "[1041, 10, 4]"
	#Comma-separated list of structures to locate with the End Remastered map
	map_structure_list = "[endrem:end_castle]"
	#Average distance in chunks between End Castles (Set to 0 to disable)
	end_castle_distance = 1024
	#Comma-separated list of whitelisted biome categories for the End Gate
	end_gate_whitelisted_biome_categories = "[none]"
	#Values for the End Remastered map trade: [minPrice, maxPrice, expGiven]
	map_trade_values = "[40, 50, 12]"
	#Sets the quantity of mobs in End Remastered Structures: "peaceful", "easy", "normal", "hard" or "hardcore"
	monster_difficulty = "hard"
	#Minimum distance in chunks between End Gates and the spawn
	end_gate_spawn_distance = 130

