
[LookInMyEyes]
	#Range: 0.0 ~ 360.0
	"ViewField(Angle, default 180°)" = 180.0
	#If enabled, PathfinderMobs would turn to the sound source when they heard sth.
	MobsCheckSoundSource = true
	#The possibility of mobs checking sound source when they heard sth.
	#Range: 0 ~ 100
	"MobsCheckSoundSourceChance(%)" = 100
	#If enabled, you will not play any sound when sneaking
	SneakNoSound = false
	#If enabled, mobs that don't have target will target the source living entity when attacked
	#Disable this may cause some strange issues between iron golems and zombies
	MobsTargetAttacker = true
	#Deaf entities that fail to hear anything
	Deaf = ["minecraft:bee", "minecraft:cave_spider", "minecraft:endermite", "minecraft:silverfish", "minecraft:spider", "alexsmobs:centipede_head", "alexsmobs:crimson_mosquito", "alexsmobs:leafcutter_ant", "alexsmobs:lobster", "alexsmobs:mantis_shrimp", "alexsmobs:tarantula_hawk", "alexsmobs:warped_mosco", "cataclysm:endermaptera", "infernalexp:glowsquito", "infernalexp:warpbeetle", "minecraft:piglin", "minecraft:piglin_brute", "bygonenether:piglin_hunter", "bygonenether:piglin_prisoner"]
	#Blind entities that fail to see anything
	Blind = []

