
#General settings
[general]
	#Range: 0.0 ~ 2.147483647E9
	damage = 2.5
	#Limits the number of times a given augment may be applied to a given effect
	#Example entry: "amplify=5"
	augment_limits = ["amplify=4"]
	#Cost
	#Range: > -2147483648
	cost = 75
	#The maximum number of times this glyph may appear in a single spell
	#Range: > 1
	per_spell_limit = 2147483647
	#Is Starter Glyph?
	starter = false
	#Damage per block in the air
	#Range: 0.0 ~ 1.7976931348623157E308
	airDamage = 0.25
	#Range: 0.0 ~ 2.147483647E9
	amplify = 2.5
	#Is Enabled?
	enabled = true

